after_success: |
  if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
    echo "$PGP_SECRET" | base64 --decode | gpg --import
    if [ -z "$TRAVIS_TAG" ]; then
        sbt publishSigned
    else
        sbt publishSigned sonatypeRelease
    fi
  fi
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  provider: releases
  api_key:
    secure: y+vmLWSPEaM/J3ysZxosMz/LYhUaXFv7pi7wtWw85A6cHi2rV29NFlPHofCfp7ZmFLyOw6PV3+KCTOrTDyVhtcvJQ49opPReUzROkaA6I00TsG01jM+RHyUMybbDm3OMu8LkMgDLDK/PqL1imBw7Bd/NztCzVL/USbetY/wSCDYK1D3uUFfcsJvcS8BCZcxnDHkHOGyJfwCA+xfNqfSBp093oIkQ847pcmgtakKbHY7s5CEILUKfJaDqSi6Iim2kGi/yW6xhFfh9oN3PAeaLmD7QoyD44ht/V5HbYQAf+n/+skH40HWUjNfrVSbBAWuTxN2qa8b2duifIlail4khc8PGFvnhkKIYih80hl5uIp2GxYx8+nylvteQik+6VJEtFOtOEwYDmmK+mgoUcbytOalHJ7cFjJhfjtw7PwdTd5mPznePsZH3Iufz1yikLUEBhBZ/Z1CjhYLane+wBxG617JoKLSS46fJj7rOS9nydJclRw5srVT7PUu88DMXxXUbNK//kIudhbTBnP2yyesyIcAkKHTscHhI1H+7hhRuLQM27/TD3Ly3um/MpQsxK6osrAbfgQuegsw7VIYdVdaArG3JrG4AzMdwooN1H3ve9FcYKikx3n6+dwRzqi9i1z7WaygtyMZ5HoRlK/Omfnp/DPRuNd2mNdHW11rxkux79RQ=
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    repo: lucidsoftware/opentracing-thread-context
    tags: true
  skip_cleanup: true
git:
  depth: 1
jdk: openjdk8
language: scala
script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
  - sbt package
